### ISSUE TITLE
Setup vanity import URL

### ISSUE THREAD

**Issue by rakyll** [census-ecosystem/opencensus-go-exporter-aws#12]
We need to setup vanity import URL for the aws package.

The plan is to move all the vendor specific code outside of the core libraries. Then, we will have a set a vanity import path server for vendor-specific and contrib packages.

**Comment by savaki** [comment]
If you're looking for a repo to model after, I think go.uber.org does a good job where go.uber.org/{project} is the basic pattern for their go projects.

**Comment by rakyll** [comment]
Initially we were thinking about providing,

go.opencensus.io/exporter/aws

But godoc has some issues given go.opencensus.io is a git repo.

We are thinking about

contrib.go.opencensus.io/exporter/aws
contrib.go.opencensus.io/exporter/stackdriver

etc and have all the vendor-specific stuff under contrib.

**Comment by savaki** [comment]
I like the initial idea of `go.opencensus.io/exporter/aws`.  Would probably mean moving the core to something like `go.opencensus.io/core` which isn't really a bad thing.

**Comment by savaki** [comment]
Closing this as it looks like everything has been converted to use the vanity url, `contrib.go.opencensus.io/exporter/aws`.
