### ISSUE TITLE
Skip integration tests

### ISSUE THREAD

**Issue by rakyll** [census-ecosystem/opencensus-go-exporter-aws#13]
I cannot run the tests because tests contain tons of integration tests. Integration tests should be skipped if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are not set.

**Comment by savaki** [comment]
My bad.  I had forgotten that I always have AWS_DEFAULT_REGION defined.

**Comment by savaki** [comment]
I'm going to go ahead and close this as I don't believe is an issue any longer.
